# Generated by Django 4.1.3 on 2022-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productinorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказ', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AddField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
