# Generated by Django 4.1.3 on 2022-11-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_productinorder_options_productinorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
