# Generated by Django 4.1.3 on 2022-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_price_productinorder_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Общая цена'),
        ),
    ]
