# Generated by Django 4.1.3 on 2022-12-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_productinorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
    ]
