# Generated by Django 4.1.3 on 2022-12-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_delete_alter_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delete',
        ),
    ]
